### ISSUE TITLE
error: esp_event.h: No such file or directory

### ISSUE THREAD

**Issue by dajewiss** [abobija/esp-discord#5]
Hi there

I'm using idf v5.0.1
esp_websocket_client (1.0.0)

I am getting a complier error-

In file included from D:/Projects/discord-test/discord-test/components/esp-discord/include/discord/private/_models.h:5,
                 from D:/Projects/discord-test/discord-test/components/esp-discord/include/discord/private/_json.h:5,
                 from D:/Projects/discord-test/discord-test/components/esp-discord/src/discord/private/_json.c:1:
D:/Projects/discord-test/discord-test/components/esp-discord/include/discord.h:5:10: fatal error: esp_event.h: No such file or directory
    5 | #include "esp_event.h"

But the project has this file in-
D:/Projects/discord-test/discord-test/components/components/esp_event/include/esp_event.h

**Comment by mstcgalis** [comment]
hello, i have the same error, did you manage to solve it? :)

**Comment by mstcgalis** [comment]
I just got a successful build by switching to ESP-IDF v4.4.4

**Comment by abobija** [comment]
#7
